title: Jaspreet Singh Dhani
logo: /profile_shot.jpeg
description: I firmly believe that every experience carries its own unique lessons. Some might involve the intracacies of turning machine learning models into production-ready giants, while others, if not almost all of them, serve as valuable building blocks for enhancing life skills and personal development.
#show_downloads: true
theme: jekyll-theme-minimal
